### ISSUE TITLE
Not support TS

### ISSUE THREAD

**Issue by maquannene** [sebastian-software/babel-plugin-smart-webpack-import#1]
If use typescript, I have to set module as 'esnext' in tsconfig to support code split.

But the plugin not work in this situation.

In js project, chunk named by file name, but in ts project, chunk beacome 0.js 1.js .....

**Comment by swernerx** [comment]
Looks like the plugin is not enabled at all. It only affects TS code processed by Babel and not by Typescript.

**Comment by maquannene** [comment]
> Looks like the plugin is not enabled at all. It only affects TS code processed by Babel and not by Typescript.

Yeah, I used ts-load before, so the plugin not work. Now change to babel-loader, work well.
