### ISSUE TITLE
Option to disable hashing

### ISSUE THREAD

**Issue by ScriptedAlchemy** [sebastian-software/babel-plugin-smart-webpack-import#2]
Hey!! So funny that we run into each other again 😂

I'm working on a new project (its still a little green) https://github.com/ScriptedAlchemy/webpack-external-import-demo

I was going to fork this project or just pull the code into my own,  but wanted to ask. Would you consider an option where the chunk-names do not have a randomized hash on the end. 

I'm aware of a higher risk of collisions, but it would allow for me to predictably know the name of a chunk. This is pretty similar to babel-plugin-universal-import, however its specifically for universal. 

Im working on a "magic export comment" which allows you to load chunks from another webpack build, much like dynamic imports. 

to reiterate -  an option in your babel plugin to disable hashing to achieve a result like: `   import(/* webpackChunkName: "Title"*/ './components/Title');`

**Comment by swernerx** [comment]
Hi!

Thanks for contacting! 
Feel free to open a PR for offering that option. Should not be the default but might make sense for some use cases to offer such a thing.

**Comment by ScriptedAlchemy** [comment]
@swernerx Its great to hear from you!!

Oh I totally agree it should not be the default - its an advanced option that would be intended for developers who understand how to cater for such option within their folder and file naming conventions. Ill open a PR as soon as i can. Would love your feedback - beautiful work on this plugin. I hope things are going well on your side of the world! :)
